# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nadeshiko_api_client.models.segment_internal import SegmentInternal

class TestSegmentInternal(unittest.TestCase):
    """SegmentInternal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SegmentInternal:
        """Test SegmentInternal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SegmentInternal`
        """
        model = SegmentInternal()
        if include_optional:
            return SegmentInternal(
                id = 120045,
                uuid = '3fd94cef-a3e1-31ae-bc8d-e743f03e9c7e',
                public_id = 'V1StGXR8_Z5d',
                position = 1133,
                status = 'ACTIVE',
                start_time_ms = 2007255,
                end_time_ms = 2008464,
                content_rating = 'SAFE',
                episode = 1,
                media_id = 7674,
                media_public_id = 'V1StGXR8_Z5d',
                text_ja = nadeshiko_api_client.models.segment_text_ja.Segment_textJa(
                    content = '僕は僕で、君は君だ。', 
                    highlight = '', 
                    tokens = [
                        nadeshiko_api_client.models.token.Token(
                            s = '食べ', 
                            d = '食べる', 
                            r = 'タベ', 
                            b = 3, 
                            e = 5, 
                            p = '動詞', 
                            p1 = '固有名詞', 
                            p2 = '人名', 
                            p4 = '五段-カ行', 
                            cf = '連用形-一般', )
                        ], ),
                text_en = nadeshiko_api_client.models.segment_text_en.Segment_textEn(
                    content = 'I am me, and you are you.', 
                    is_machine_translated = False, 
                    highlight = '', ),
                text_es = nadeshiko_api_client.models.segment_text_es.Segment_textEs(
                    content = 'Yo soy yo, y tú eres tú.', 
                    is_machine_translated = False, 
                    highlight = '', ),
                urls = nadeshiko_api_client.models.segment_urls.Segment_urls(
                    image_url = '', 
                    audio_url = '', 
                    video_url = '', ),
                storage = 'R2',
                hashed_id = '0d39e46b14',
                storage_base_path = 'anime/steins-gate',
                rating_analysis = { },
                pos_analysis = { }
            )
        else:
            return SegmentInternal(
                id = 120045,
                uuid = '3fd94cef-a3e1-31ae-bc8d-e743f03e9c7e',
                public_id = 'V1StGXR8_Z5d',
                position = 1133,
                status = 'ACTIVE',
                start_time_ms = 2007255,
                end_time_ms = 2008464,
                content_rating = 'SAFE',
                episode = 1,
                media_id = 7674,
                media_public_id = 'V1StGXR8_Z5d',
                text_ja = nadeshiko_api_client.models.segment_text_ja.Segment_textJa(
                    content = '僕は僕で、君は君だ。', 
                    highlight = '', 
                    tokens = [
                        nadeshiko_api_client.models.token.Token(
                            s = '食べ', 
                            d = '食べる', 
                            r = 'タベ', 
                            b = 3, 
                            e = 5, 
                            p = '動詞', 
                            p1 = '固有名詞', 
                            p2 = '人名', 
                            p4 = '五段-カ行', 
                            cf = '連用形-一般', )
                        ], ),
                text_en = nadeshiko_api_client.models.segment_text_en.Segment_textEn(
                    content = 'I am me, and you are you.', 
                    is_machine_translated = False, 
                    highlight = '', ),
                text_es = nadeshiko_api_client.models.segment_text_es.Segment_textEs(
                    content = 'Yo soy yo, y tú eres tú.', 
                    is_machine_translated = False, 
                    highlight = '', ),
                urls = nadeshiko_api_client.models.segment_urls.Segment_urls(
                    image_url = '', 
                    audio_url = '', 
                    video_url = '', ),
        )
        """

    def testSegmentInternal(self):
        """Test SegmentInternal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
