# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nadeshiko_api_client.models.seiyuu import Seiyuu

class TestSeiyuu(unittest.TestCase):
    """Seiyuu unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Seiyuu:
        """Test Seiyuu
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Seiyuu`
        """
        model = Seiyuu()
        if include_optional:
            return Seiyuu(
                id = 1,
                public_id = 'V1StGXR8_Z5d',
                external_ids = nadeshiko_api_client.models.external_id.ExternalId(
                    anilist = '21459', 
                    imdb = 'tt1234567', 
                    tvdb = '12345', 
                    tmdb = '90955', ),
                name_ja = '阿部敦',
                name_en = 'Atsushi Abe',
                image_url = 'https://s4.anilist.co/file/anilistcdn/staff/large/n95991.jpg'
            )
        else:
            return Seiyuu(
                id = 1,
                public_id = 'V1StGXR8_Z5d',
                external_ids = nadeshiko_api_client.models.external_id.ExternalId(
                    anilist = '21459', 
                    imdb = 'tt1234567', 
                    tvdb = '12345', 
                    tmdb = '90955', ),
                name_ja = '阿部敦',
                name_en = 'Atsushi Abe',
                image_url = 'https://s4.anilist.co/file/anilistcdn/staff/large/n95991.jpg',
        )
        """

    def testSeiyuu(self):
        """Test Seiyuu"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
