# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nadeshiko_api_client.models.episode import Episode

class TestEpisode(unittest.TestCase):
    """Episode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Episode:
        """Test Episode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Episode`
        """
        model = Episode()
        if include_optional:
            return Episode(
                media_id = 7674,
                episode_number = 1,
                title_en = 'The Beginning',
                title_romaji = 'Hajimari',
                title_ja = '始まり',
                description = 'The hero begins their journey',
                aired_at = '2024-01-15T09:00:00Z',
                length_seconds = 1420,
                thumbnail_url = 'https://example.com/thumbnails/episode1.jpg',
                segment_count = 450
            )
        else:
            return Episode(
                media_id = 7674,
                episode_number = 1,
                segment_count = 450,
        )
        """

    def testEpisode(self):
        """Test Episode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
