# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nadeshiko_api_client.api.media_api import MediaApi


class TestMediaApi(unittest.TestCase):
    """MediaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MediaApi()

    def tearDown(self) -> None:
        pass

    def test_get_episode(self) -> None:
        """Test case for get_episode

        Get single episode
        """
        pass

    def test_get_media(self) -> None:
        """Test case for get_media

        Get single media
        """
        pass

    def test_get_segment(self) -> None:
        """Test case for get_segment

        Get single segment
        """
        pass

    def test_get_segment_by_uuid(self) -> None:
        """Test case for get_segment_by_uuid

        Get segment by publicId
        """
        pass

    def test_get_segment_context(self) -> None:
        """Test case for get_segment_context

        Get surrounding context for a segment
        """
        pass

    def test_get_series(self) -> None:
        """Test case for get_series

        Get series details
        """
        pass

    def test_list_episodes(self) -> None:
        """Test case for list_episodes

        List episodes for a media
        """
        pass

    def test_list_media(self) -> None:
        """Test case for list_media

        List all media
        """
        pass

    def test_list_series(self) -> None:
        """Test case for list_series

        List all series
        """
        pass


if __name__ == '__main__':
    unittest.main()
