# coding: utf-8

"""
    Nadeshiko API

    Welcome to the Nadeshiko API.   ## Getting Started  Nadeshiko uses API keys to grant access to the API. Authentication is performed using the Authorization header. Please note that you must be registered on Nadeshiko to generate an API key. If you haven't registered yet, please do so.  If you haven't generated an API key yet, you can do so on your [account page](https://nadeshiko.co/settings/api), API section.  ### Quotas and Limits The API has a rate limit to ensure fair usage. Each API key is subject to a rate limit of 2000 requests per 5 minutes. Exceeding this limit will result in a temporary block with the following message:  > \"Too many requests. Please try again later.\"  Additionally, each account has a monthly quota limit based on the user's roles. Once the monthly quota is exceeded, the API key will be temporarily disabled for the rest of the month, and any further requests will receive the message:  > \"API Key quota exceeded for this month.\"  | Role         | Quota (Monthly) | |--------------|-----------------| | Normal User  | 5000 requests   |  To increase your quota, please contact the Nadeshiko team. For more information, refer to the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 1.0.0
    Contact: marc@scalar.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nadeshiko_api_client.models.response_v1 import ResponseV1

class TestResponseV1(unittest.TestCase):
    """ResponseV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseV1:
        """Test ResponseV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseV1`
        """
        model = ResponseV1()
        if include_optional:
            return ResponseV1(
                statistics = [
                    {anime_id=5, category=1, name_anime_romaji=Steins;Gate, name_anime_en=Steins;Gate, name_anime_jp=シュタインズ・ゲート, amount_sentences_found=18, season_with_episode_hits={1={5=2, 8=2, 12=1, 16=2, 17=1, 18=1, 20=1, 22=3, 23=4, 24=1}}}
                    ],
                category_statistics = [
                    {category=1, count=99}
                    ],
                sentences = [
                    {basic_info={id_anime=110316, name_anime_romaji=Alice in Borderland, name_anime_en=Alice in Borderland, name_anime_jp=今際の国のアリス, cover=https://api.brigadasos.xyz/api/media/jdrama/alice-in-borderland\cover.jpg, banner=https://api.brigadasos.xyz/api/media/jdrama/alice-in-borderland\banner.jpg, episode=5, season=1, category=3}, segment_info={status=1, uuid=3fd94cef-a3e1-31ae-bc8d-e743f03e9c7e, position=1133, start_time=0:33:52.822000, end_time=0:33:53.906000, content_jp=彼女?, content_jp_highlight=<em>彼女</em>?, content_en=Your girlfriend?, content_en_highlight=, content_en_mt=false, content_es=¿Es tu novia?, content_es_highlight=, content_es_mt=false, is_nsfw=false, actor_ja=, actor_en=, actor_es=}, media_info={path_image=https://api.brigadasos.xyz/api/media/jdrama/alice-in-borderland/S01/E05/1133.webp, path_audio=https://api.brigadasos.xyz/api/media/jdrama/alice-in-borderland/S01/E05/1133.mp3, path_video=https://api.brigadasos.xyz/api/media/jdrama/alice-in-borderland/S01/E05/1133.mp4}}
                    ],
                cursor = [
                    1.337
                    ]
            )
        else:
            return ResponseV1(
        )
        """

    def testResponseV1(self):
        """Test ResponseV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
