# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nadeshiko_api_client.models.media import Media

class TestMedia(unittest.TestCase):
    """Media unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Media:
        """Test Media
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Media`
        """
        model = Media()
        if include_optional:
            return Media(
                id = 7674,
                public_id = 'V1StGXR8_Z5d',
                external_ids = nadeshiko_api_client.models.external_id.ExternalId(
                    anilist = '21459', 
                    imdb = 'tt1234567', 
                    tvdb = '12345', 
                    tmdb = '90955', ),
                name_ja = 'バクマン。',
                name_romaji = 'Bakuman.',
                name_en = 'Bakuman.',
                airing_format = 'TV',
                airing_status = 'FINISHED',
                genres = [Comedy, Drama, Romance, Slice of Life],
                cover_url = 'https://cdn.example.com/media/anime/bakuman/cover.webp',
                banner_url = 'https://cdn.example.com/media/anime/bakuman/banner.webp',
                start_date = '2010-10-02',
                end_date = '2011-04-02',
                category = 'ANIME',
                segment_count = 0,
                episode_count = 25,
                studio = 'J.C.STAFF',
                season_name = 'FALL',
                season_year = 2010,
                characters = [
                    nadeshiko_api_client.models.media_character.MediaCharacter(
                        id = 14545, 
                        name_ja = '真城最高', 
                        name_en = 'Moritaka Mashiro', 
                        image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b14545.jpg', 
                        seiyuu = nadeshiko_api_client.models.seiyuu.Seiyuu(
                            id = 1, 
                            public_id = 'V1StGXR8_Z5d', 
                            external_ids = nadeshiko_api_client.models.external_id.ExternalId(
                                anilist = '21459', 
                                imdb = 'tt1234567', 
                                tvdb = '12345', 
                                tmdb = '90955', ), 
                            name_ja = '阿部敦', 
                            name_en = 'Atsushi Abe', 
                            image_url = 'https://s4.anilist.co/file/anilistcdn/staff/large/n95991.jpg', ), 
                        role = 'MAIN', )
                    ]
            )
        else:
            return Media(
                id = 7674,
                public_id = 'V1StGXR8_Z5d',
                external_ids = nadeshiko_api_client.models.external_id.ExternalId(
                    anilist = '21459', 
                    imdb = 'tt1234567', 
                    tvdb = '12345', 
                    tmdb = '90955', ),
                name_ja = 'バクマン。',
                name_romaji = 'Bakuman.',
                name_en = 'Bakuman.',
                airing_format = 'TV',
                airing_status = 'FINISHED',
                genres = [Comedy, Drama, Romance, Slice of Life],
                cover_url = 'https://cdn.example.com/media/anime/bakuman/cover.webp',
                banner_url = 'https://cdn.example.com/media/anime/bakuman/banner.webp',
                start_date = '2010-10-02',
                category = 'ANIME',
                segment_count = 0,
                episode_count = 25,
                season_name = 'FALL',
                season_year = 2010,
        )
        """

    def testMedia(self):
        """Test Media"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
