# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nadeshiko_api_client.api.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()

    def tearDown(self) -> None:
        pass

    def test_get_search_stats(self) -> None:
        """Test case for get_search_stats

        Get search statistics
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        Search segments by query
        """
        pass

    def test_search_words(self) -> None:
        """Test case for search_words

        Search by multiple words
        """
        pass


if __name__ == '__main__':
    unittest.main()
