# coding: utf-8

"""
    Nadeshiko API

    Welcome to the Nadeshiko API.   ## Getting Started  Nadeshiko uses API keys to grant access to the API. Authentication is performed using the Authorization header. Please note that you must be registered on Nadeshiko to generate an API key. If you haven't registered yet, please do so.  If you haven't generated an API key yet, you can do so on your [account page](https://nadeshiko.co/settings/api), API section.  ### Quotas and Limits The API has a rate limit to ensure fair usage. Each API key is subject to a rate limit of 2000 requests per 5 minutes. Exceeding this limit will result in a temporary block with the following message:  > \"Too many requests. Please try again later.\"  Additionally, each account has a monthly quota limit based on the user's roles. Once the monthly quota is exceeded, the API key will be temporarily disabled for the rest of the month, and any further requests will receive the message:  > \"API Key quota exceeded for this month.\"  | Role         | Quota (Monthly) | |--------------|-----------------| | Normal User  | 5000 requests   |  To increase your quota, please contact the Nadeshiko team. For more information, refer to the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 1.0.0
    Contact: marc@scalar.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nadeshiko_api_client.models.statistic import Statistic

class TestStatistic(unittest.TestCase):
    """Statistic unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Statistic:
        """Test Statistic
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Statistic`
        """
        model = Statistic()
        if include_optional:
            return Statistic(
                anime_id = 56,
                category = 56,
                name_anime_romaji = '',
                name_anime_en = '',
                name_anime_jp = '',
                amount_sentences_found = 56,
                season_with_episode_hits = {
                    'key' : {
                        'key' : 56
                        }
                    }
            )
        else:
            return Statistic(
        )
        """

    def testStatistic(self):
        """Test Statistic"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
