# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nadeshiko_api_client.models.segment_context_response import SegmentContextResponse

class TestSegmentContextResponse(unittest.TestCase):
    """SegmentContextResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SegmentContextResponse:
        """Test SegmentContextResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SegmentContextResponse`
        """
        model = SegmentContextResponse()
        if include_optional:
            return SegmentContextResponse(
                segments = [
                    nadeshiko_api_client.models.segment.Segment(
                        id = 120045, 
                        uuid = '3fd94cef-a3e1-31ae-bc8d-e743f03e9c7e', 
                        public_id = 'V1StGXR8_Z5d', 
                        position = 1133, 
                        status = 'ACTIVE', 
                        start_time_ms = 2007255, 
                        end_time_ms = 2008464, 
                        content_rating = 'SAFE', 
                        episode = 1, 
                        media_id = 7674, 
                        media_public_id = 'V1StGXR8_Z5d', 
                        text_ja = nadeshiko_api_client.models.segment_text_ja.Segment_textJa(
                            content = '僕は僕で、君は君だ。', 
                            highlight = '', 
                            tokens = [
                                nadeshiko_api_client.models.token.Token(
                                    s = '食べ', 
                                    d = '食べる', 
                                    r = 'タベ', 
                                    b = 3, 
                                    e = 5, 
                                    p = '動詞', 
                                    p1 = '固有名詞', 
                                    p2 = '人名', 
                                    p4 = '五段-カ行', 
                                    cf = '連用形-一般', )
                                ], ), 
                        text_en = nadeshiko_api_client.models.segment_text_en.Segment_textEn(
                            content = 'I am me, and you are you.', 
                            is_machine_translated = False, 
                            highlight = '', ), 
                        text_es = nadeshiko_api_client.models.segment_text_es.Segment_textEs(
                            content = 'Yo soy yo, y tú eres tú.', 
                            is_machine_translated = False, 
                            highlight = '', ), 
                        urls = nadeshiko_api_client.models.segment_urls.Segment_urls(
                            image_url = '', 
                            audio_url = '', 
                            video_url = '', ), )
                    ],
                includes = nadeshiko_api_client.models.segment_context_response_includes.SegmentContextResponse_includes(
                    media = {
                        'key' : nadeshiko_api_client.models.media.Media(
                            id = 7674, 
                            public_id = 'V1StGXR8_Z5d', 
                            external_ids = nadeshiko_api_client.models.external_id.ExternalId(
                                anilist = '21459', 
                                imdb = 'tt1234567', 
                                tvdb = '12345', 
                                tmdb = '90955', ), 
                            name_ja = 'バクマン。', 
                            name_romaji = 'Bakuman.', 
                            name_en = 'Bakuman.', 
                            airing_format = 'TV', 
                            airing_status = 'FINISHED', 
                            genres = [Comedy, Drama, Romance, Slice of Life], 
                            cover_url = 'https://cdn.example.com/media/anime/bakuman/cover.webp', 
                            banner_url = 'https://cdn.example.com/media/anime/bakuman/banner.webp', 
                            start_date = '2010-10-02', 
                            end_date = '2011-04-02', 
                            category = 'ANIME', 
                            segment_count = 0, 
                            episode_count = 25, 
                            studio = 'J.C.STAFF', 
                            season_name = 'FALL', 
                            season_year = 2010, 
                            characters = [
                                nadeshiko_api_client.models.media_character.MediaCharacter(
                                    id = 14545, 
                                    name_ja = '真城最高', 
                                    name_en = 'Moritaka Mashiro', 
                                    image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b14545.jpg', 
                                    seiyuu = nadeshiko_api_client.models.seiyuu.Seiyuu(
                                        id = 1, 
                                        public_id = 'V1StGXR8_Z5d', 
                                        external_ids = nadeshiko_api_client.models.external_id.ExternalId(
                                            anilist = '21459', 
                                            imdb = 'tt1234567', 
                                            tvdb = '12345', 
                                            tmdb = '90955', ), 
                                        name_ja = '阿部敦', 
                                        name_en = 'Atsushi Abe', 
                                        image_url = 'https://s4.anilist.co/file/anilistcdn/staff/large/n95991.jpg', ), 
                                    role = 'MAIN', )
                                ], )
                        }, )
            )
        else:
            return SegmentContextResponse(
                segments = [
                    nadeshiko_api_client.models.segment.Segment(
                        id = 120045, 
                        uuid = '3fd94cef-a3e1-31ae-bc8d-e743f03e9c7e', 
                        public_id = 'V1StGXR8_Z5d', 
                        position = 1133, 
                        status = 'ACTIVE', 
                        start_time_ms = 2007255, 
                        end_time_ms = 2008464, 
                        content_rating = 'SAFE', 
                        episode = 1, 
                        media_id = 7674, 
                        media_public_id = 'V1StGXR8_Z5d', 
                        text_ja = nadeshiko_api_client.models.segment_text_ja.Segment_textJa(
                            content = '僕は僕で、君は君だ。', 
                            highlight = '', 
                            tokens = [
                                nadeshiko_api_client.models.token.Token(
                                    s = '食べ', 
                                    d = '食べる', 
                                    r = 'タベ', 
                                    b = 3, 
                                    e = 5, 
                                    p = '動詞', 
                                    p1 = '固有名詞', 
                                    p2 = '人名', 
                                    p4 = '五段-カ行', 
                                    cf = '連用形-一般', )
                                ], ), 
                        text_en = nadeshiko_api_client.models.segment_text_en.Segment_textEn(
                            content = 'I am me, and you are you.', 
                            is_machine_translated = False, 
                            highlight = '', ), 
                        text_es = nadeshiko_api_client.models.segment_text_es.Segment_textEs(
                            content = 'Yo soy yo, y tú eres tú.', 
                            is_machine_translated = False, 
                            highlight = '', ), 
                        urls = nadeshiko_api_client.models.segment_urls.Segment_urls(
                            image_url = '', 
                            audio_url = '', 
                            video_url = '', ), )
                    ],
                includes = nadeshiko_api_client.models.segment_context_response_includes.SegmentContextResponse_includes(
                    media = {
                        'key' : nadeshiko_api_client.models.media.Media(
                            id = 7674, 
                            public_id = 'V1StGXR8_Z5d', 
                            external_ids = nadeshiko_api_client.models.external_id.ExternalId(
                                anilist = '21459', 
                                imdb = 'tt1234567', 
                                tvdb = '12345', 
                                tmdb = '90955', ), 
                            name_ja = 'バクマン。', 
                            name_romaji = 'Bakuman.', 
                            name_en = 'Bakuman.', 
                            airing_format = 'TV', 
                            airing_status = 'FINISHED', 
                            genres = [Comedy, Drama, Romance, Slice of Life], 
                            cover_url = 'https://cdn.example.com/media/anime/bakuman/cover.webp', 
                            banner_url = 'https://cdn.example.com/media/anime/bakuman/banner.webp', 
                            start_date = '2010-10-02', 
                            end_date = '2011-04-02', 
                            category = 'ANIME', 
                            segment_count = 0, 
                            episode_count = 25, 
                            studio = 'J.C.STAFF', 
                            season_name = 'FALL', 
                            season_year = 2010, 
                            characters = [
                                nadeshiko_api_client.models.media_character.MediaCharacter(
                                    id = 14545, 
                                    name_ja = '真城最高', 
                                    name_en = 'Moritaka Mashiro', 
                                    image_url = 'https://s4.anilist.co/file/anilistcdn/character/large/b14545.jpg', 
                                    seiyuu = nadeshiko_api_client.models.seiyuu.Seiyuu(
                                        id = 1, 
                                        public_id = 'V1StGXR8_Z5d', 
                                        external_ids = nadeshiko_api_client.models.external_id.ExternalId(
                                            anilist = '21459', 
                                            imdb = 'tt1234567', 
                                            tvdb = '12345', 
                                            tmdb = '90955', ), 
                                        name_ja = '阿部敦', 
                                        name_en = 'Atsushi Abe', 
                                        image_url = 'https://s4.anilist.co/file/anilistcdn/staff/large/n95991.jpg', ), 
                                    role = 'MAIN', )
                                ], )
                        }, ),
        )
        """

    def testSegmentContextResponse(self):
        """Test SegmentContextResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
