# coding: utf-8

"""
    Nadeshiko API

    Welcome to the Nadeshiko API.   ## Getting Started  Nadeshiko uses API keys to grant access to the API. Authentication is performed using the Authorization header. Please note that you must be registered on Nadeshiko to generate an API key. If you haven't registered yet, please do so.  If you haven't generated an API key yet, you can do so on your [account page](https://nadeshiko.co/settings/api), API section.  ### Quotas and Limits The API has a rate limit to ensure fair usage. Each API key is subject to a rate limit of 2000 requests per 5 minutes. Exceeding this limit will result in a temporary block with the following message:  > \"Too many requests. Please try again later.\"  Additionally, each account has a monthly quota limit based on the user's roles. Once the monthly quota is exceeded, the API key will be temporarily disabled for the rest of the month, and any further requests will receive the message:  > \"API Key quota exceeded for this month.\"  | Role         | Quota (Monthly) | |--------------|-----------------| | Normal User  | 5000 requests   |  To increase your quota, please contact the Nadeshiko team. For more information, refer to the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 1.0.0
    Contact: marc@scalar.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nadeshiko_api_client.api.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()

    def tearDown(self) -> None:
        pass

    def test_get_context_sentence(self) -> None:
        """Test case for get_context_sentence

        Get context for a sentence
        """
        pass

    def test_get_recent_media(self) -> None:
        """Test case for get_recent_media

        Get recent media
        """
        pass

    def test_search_multiple_words(self) -> None:
        """Test case for search_multiple_words

        Search by multiple queries
        """
        pass

    def test_search_sentence(self) -> None:
        """Test case for search_sentence

        Search by query
        """
        pass


if __name__ == '__main__':
    unittest.main()
