# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from nadeshiko_api_client.models.search_filters_media import SearchFiltersMedia

class TestSearchFiltersMedia(unittest.TestCase):
    """SearchFiltersMedia unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchFiltersMedia:
        """Test SearchFiltersMedia
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchFiltersMedia`
        """
        model = SearchFiltersMedia()
        if include_optional:
            return SearchFiltersMedia(
                include = [
                    nadeshiko_api_client.models.media_filter_item.MediaFilterItem(
                        media_id = 'abc123xyz', 
                        episodes = [1, 2], )
                    ],
                exclude = [
                    nadeshiko_api_client.models.media_filter_item.MediaFilterItem(
                        media_id = 'abc123xyz', 
                        episodes = [1, 2], )
                    ]
            )
        else:
            return SearchFiltersMedia(
        )
        """

    def testSearchFiltersMedia(self):
        """Test SearchFiltersMedia"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
