# coding: utf-8

# flake8: noqa
"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from nadeshiko_api_client.models.category import Category
from nadeshiko_api_client.models.category_count import CategoryCount
from nadeshiko_api_client.models.content_rating import ContentRating
from nadeshiko_api_client.models.episode import Episode
from nadeshiko_api_client.models.episode_list_response import EpisodeListResponse
from nadeshiko_api_client.models.error400 import Error400
from nadeshiko_api_client.models.error401 import Error401
from nadeshiko_api_client.models.error403 import Error403
from nadeshiko_api_client.models.error404 import Error404
from nadeshiko_api_client.models.error429 import Error429
from nadeshiko_api_client.models.error500 import Error500
from nadeshiko_api_client.models.external_id import ExternalId
from nadeshiko_api_client.models.include_expansion import IncludeExpansion
from nadeshiko_api_client.models.media import Media
from nadeshiko_api_client.models.media_character import MediaCharacter
from nadeshiko_api_client.models.media_filter_item import MediaFilterItem
from nadeshiko_api_client.models.media_include_expansion import MediaIncludeExpansion
from nadeshiko_api_client.models.media_list_response import MediaListResponse
from nadeshiko_api_client.models.media_list_response_stats import MediaListResponseStats
from nadeshiko_api_client.models.media_search_stats import MediaSearchStats
from nadeshiko_api_client.models.opaque_cursor_pagination import OpaqueCursorPagination
from nadeshiko_api_client.models.pagination_info import PaginationInfo
from nadeshiko_api_client.models.search_filters import SearchFilters
from nadeshiko_api_client.models.search_filters_languages import SearchFiltersLanguages
from nadeshiko_api_client.models.search_filters_media import SearchFiltersMedia
from nadeshiko_api_client.models.search_filters_segment_duration_ms import SearchFiltersSegmentDurationMs
from nadeshiko_api_client.models.search_filters_segment_length_chars import SearchFiltersSegmentLengthChars
from nadeshiko_api_client.models.search_multiple_request import SearchMultipleRequest
from nadeshiko_api_client.models.search_multiple_request_query import SearchMultipleRequestQuery
from nadeshiko_api_client.models.search_multiple_response import SearchMultipleResponse
from nadeshiko_api_client.models.search_multiple_response_includes import SearchMultipleResponseIncludes
from nadeshiko_api_client.models.search_request import SearchRequest
from nadeshiko_api_client.models.search_request_query import SearchRequestQuery
from nadeshiko_api_client.models.search_request_sort import SearchRequestSort
from nadeshiko_api_client.models.search_response import SearchResponse
from nadeshiko_api_client.models.search_response_includes import SearchResponseIncludes
from nadeshiko_api_client.models.search_stats_request import SearchStatsRequest
from nadeshiko_api_client.models.search_stats_request_query import SearchStatsRequestQuery
from nadeshiko_api_client.models.search_stats_response import SearchStatsResponse
from nadeshiko_api_client.models.segment import Segment
from nadeshiko_api_client.models.segment_context_response import SegmentContextResponse
from nadeshiko_api_client.models.segment_context_response_includes import SegmentContextResponseIncludes
from nadeshiko_api_client.models.segment_internal import SegmentInternal
from nadeshiko_api_client.models.segment_text_en import SegmentTextEn
from nadeshiko_api_client.models.segment_text_es import SegmentTextEs
from nadeshiko_api_client.models.segment_text_ja import SegmentTextJa
from nadeshiko_api_client.models.segment_urls import SegmentUrls
from nadeshiko_api_client.models.seiyuu import Seiyuu
from nadeshiko_api_client.models.series import Series
from nadeshiko_api_client.models.series_list_response import SeriesListResponse
from nadeshiko_api_client.models.series_with_media import SeriesWithMedia
from nadeshiko_api_client.models.series_with_media_media_inner import SeriesWithMediaMediaInner
from nadeshiko_api_client.models.token import Token
from nadeshiko_api_client.models.word_match import WordMatch
from nadeshiko_api_client.models.word_match_media import WordMatchMedia

