# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Error400(BaseModel):
    """
    Bad Request error response
    """ # noqa: E501
    code: StrictStr = Field(description="Specific error code for programmatic handling")
    title: StrictStr = Field(description="A short, human-readable summary of the problem")
    detail: StrictStr = Field(description="A human-readable explanation specific to this occurrence")
    type: Optional[StrictStr] = Field(default=None, description="A URI reference that identifies the problem type (e.g., GitHub issues link)")
    instance: Optional[StrictStr] = Field(default=None, description="A URI reference that identifies the specific occurrence (e.g., trace ID)")
    status: StrictInt = Field(description="The HTTP status code")
    errors: Optional[Dict[str, StrictStr]] = Field(default=None, description="Optional map of field names to their error messages (for validation errors)")
    __properties: ClassVar[List[str]] = ["code", "title", "detail", "type", "instance", "status", "errors"]

    @field_validator('code')
    def code_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['VALIDATION_FAILED', 'INVALID_JSON', 'INVALID_REQUEST']):
            raise ValueError("must be one of enum values ('VALIDATION_FAILED', 'INVALID_JSON', 'INVALID_REQUEST')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set([400]):
            raise ValueError("must be one of enum values (400)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Error400 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Error400 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "title": obj.get("title"),
            "detail": obj.get("detail"),
            "type": obj.get("type"),
            "instance": obj.get("instance"),
            "status": obj.get("status"),
            "errors": obj.get("errors")
        })
        return _obj


