# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from nadeshiko_api_client.models.category import Category
from nadeshiko_api_client.models.external_id import ExternalId
from nadeshiko_api_client.models.media_character import MediaCharacter
from typing import Optional, Set
from typing_extensions import Self

class Media(BaseModel):
    """
    Media entry with full metadata
    """ # noqa: E501
    id: StrictInt = Field(description="Internal unique identifier for the media")
    public_id: StrictStr = Field(description="Public identifier for the media (use this in public URLs)", alias="publicId")
    external_ids: ExternalId = Field(alias="externalIds")
    name_ja: StrictStr = Field(description="Original Japanese name of the media", alias="nameJa")
    name_romaji: StrictStr = Field(description="Romaji transliteration of the media name", alias="nameRomaji")
    name_en: StrictStr = Field(description="English name of the media", alias="nameEn")
    airing_format: StrictStr = Field(description="Format of the media release (e.g., TV, OVA, Movie)", alias="airingFormat")
    airing_status: StrictStr = Field(description="Current airing status (FINISHED, RELEASING, NOT_YET_RELEASED, CANCELLED)", alias="airingStatus")
    genres: List[StrictStr] = Field(description="List of genres associated with the media")
    cover_url: StrictStr = Field(description="Full URL to the cover image", alias="coverUrl")
    banner_url: StrictStr = Field(description="Full URL to the banner image", alias="bannerUrl")
    start_date: date = Field(description="Start date of the media (first airing/release)", alias="startDate")
    end_date: Optional[date] = Field(default=None, description="End date of the media (last airing/release)", alias="endDate")
    category: Category
    segment_count: StrictInt = Field(description="Total number of subtitle segments available", alias="segmentCount")
    episode_count: StrictInt = Field(description="Total number of episodes available", alias="episodeCount")
    studio: Optional[StrictStr] = Field(default=None, description="Animation studio that produced the media")
    season_name: StrictStr = Field(description="Airing season label for the media", alias="seasonName")
    season_year: StrictInt = Field(description="Airing year for the media", alias="seasonYear")
    characters: Optional[List[MediaCharacter]] = Field(default=None, description="Characters appearing in the media with their voice actors")
    __properties: ClassVar[List[str]] = ["id", "publicId", "externalIds", "nameJa", "nameRomaji", "nameEn", "airingFormat", "airingStatus", "genres", "coverUrl", "bannerUrl", "startDate", "endDate", "category", "segmentCount", "episodeCount", "studio", "seasonName", "seasonYear", "characters"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Media from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of external_ids
        if self.external_ids:
            _dict['externalIds'] = self.external_ids.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in characters (list)
        _items = []
        if self.characters:
            for _item_characters in self.characters:
                if _item_characters:
                    _items.append(_item_characters.to_dict())
            _dict['characters'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Media from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "publicId": obj.get("publicId"),
            "externalIds": ExternalId.from_dict(obj["externalIds"]) if obj.get("externalIds") is not None else None,
            "nameJa": obj.get("nameJa"),
            "nameRomaji": obj.get("nameRomaji"),
            "nameEn": obj.get("nameEn"),
            "airingFormat": obj.get("airingFormat"),
            "airingStatus": obj.get("airingStatus"),
            "genres": obj.get("genres"),
            "coverUrl": obj.get("coverUrl"),
            "bannerUrl": obj.get("bannerUrl"),
            "startDate": obj.get("startDate"),
            "endDate": obj.get("endDate"),
            "category": obj.get("category"),
            "segmentCount": obj.get("segmentCount"),
            "episodeCount": obj.get("episodeCount"),
            "studio": obj.get("studio"),
            "seasonName": obj.get("seasonName"),
            "seasonYear": obj.get("seasonYear"),
            "characters": [MediaCharacter.from_dict(_item) for _item in obj["characters"]] if obj.get("characters") is not None else None
        })
        return _obj


