# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from nadeshiko_api_client.models.seiyuu import Seiyuu
from typing import Optional, Set
from typing_extensions import Self

class MediaCharacter(BaseModel):
    """
    Character appearing in a media with their voice actor and role
    """ # noqa: E501
    id: StrictInt = Field(description="AniList character ID")
    name_ja: StrictStr = Field(description="Japanese name of the character", alias="nameJa")
    name_en: StrictStr = Field(description="English name of the character", alias="nameEn")
    image_url: StrictStr = Field(description="Character image URL", alias="imageUrl")
    seiyuu: Seiyuu
    role: StrictStr = Field(description="Character's role in the media")
    __properties: ClassVar[List[str]] = ["id", "nameJa", "nameEn", "imageUrl", "seiyuu", "role"]

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['MAIN', 'SUPPORTING', 'BACKGROUND']):
            raise ValueError("must be one of enum values ('MAIN', 'SUPPORTING', 'BACKGROUND')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MediaCharacter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of seiyuu
        if self.seiyuu:
            _dict['seiyuu'] = self.seiyuu.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MediaCharacter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "nameJa": obj.get("nameJa"),
            "nameEn": obj.get("nameEn"),
            "imageUrl": obj.get("imageUrl"),
            "seiyuu": Seiyuu.from_dict(obj["seiyuu"]) if obj.get("seiyuu") is not None else None,
            "role": obj.get("role")
        })
        return _obj


