# coding: utf-8

"""
    Nadeshiko API

    Welcome to the Nadeshiko API.   ## Getting Started  Nadeshiko uses API keys to grant access to the API. Authentication is performed using the Authorization header. Please note that you must be registered on Nadeshiko to generate an API key. If you haven't registered yet, please do so.  If you haven't generated an API key yet, you can do so on your [account page](https://nadeshiko.co/settings/api), API section.  ### Quotas and Limits The API has a rate limit to ensure fair usage. Each API key is subject to a rate limit of 2000 requests per 5 minutes. Exceeding this limit will result in a temporary block with the following message:  > \"Too many requests. Please try again later.\"  Additionally, each account has a monthly quota limit based on the user's roles. Once the monthly quota is exceeded, the API key will be temporarily disabled for the rest of the month, and any further requests will receive the message:  > \"API Key quota exceeded for this month.\"  | Role         | Quota (Monthly) | |--------------|-----------------| | Normal User  | 5000 requests   |  To increase your quota, please contact the Nadeshiko team. For more information, refer to the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 1.0.0
    Contact: marc@scalar.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from nadeshiko_api_client.models.category_statistic import CategoryStatistic
from nadeshiko_api_client.models.sentence import Sentence
from nadeshiko_api_client.models.statistic import Statistic
from typing import Optional, Set
from typing_extensions import Self

class ResponseV1(BaseModel):
    """
    ResponseV1
    """ # noqa: E501
    statistics: Optional[List[Statistic]] = None
    category_statistics: Optional[List[CategoryStatistic]] = Field(default=None, alias="categoryStatistics")
    sentences: Optional[List[Sentence]] = None
    cursor: Optional[List[Union[StrictFloat, StrictInt]]] = None
    __properties: ClassVar[List[str]] = ["statistics", "categoryStatistics", "sentences", "cursor"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponseV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in statistics (list)
        _items = []
        if self.statistics:
            for _item_statistics in self.statistics:
                if _item_statistics:
                    _items.append(_item_statistics.to_dict())
            _dict['statistics'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in category_statistics (list)
        _items = []
        if self.category_statistics:
            for _item_category_statistics in self.category_statistics:
                if _item_category_statistics:
                    _items.append(_item_category_statistics.to_dict())
            _dict['categoryStatistics'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sentences (list)
        _items = []
        if self.sentences:
            for _item_sentences in self.sentences:
                if _item_sentences:
                    _items.append(_item_sentences.to_dict())
            _dict['sentences'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponseV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "statistics": [Statistic.from_dict(_item) for _item in obj["statistics"]] if obj.get("statistics") is not None else None,
            "categoryStatistics": [CategoryStatistic.from_dict(_item) for _item in obj["categoryStatistics"]] if obj.get("categoryStatistics") is not None else None,
            "sentences": [Sentence.from_dict(_item) for _item in obj["sentences"]] if obj.get("sentences") is not None else None,
            "cursor": obj.get("cursor")
        })
        return _obj


