# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from nadeshiko_api_client.models.category import Category
from nadeshiko_api_client.models.content_rating import ContentRating
from nadeshiko_api_client.models.search_filters_languages import SearchFiltersLanguages
from nadeshiko_api_client.models.search_filters_media import SearchFiltersMedia
from nadeshiko_api_client.models.search_filters_segment_duration_ms import SearchFiltersSegmentDurationMs
from nadeshiko_api_client.models.search_filters_segment_length_chars import SearchFiltersSegmentLengthChars
from typing import Optional, Set
from typing_extensions import Self

class SearchFilters(BaseModel):
    """
    Search filters for narrowing segment results
    """ # noqa: E501
    media: Optional[SearchFiltersMedia] = None
    category: Optional[List[Category]] = Field(default=None, description="Media category filter")
    content_rating: Optional[List[ContentRating]] = Field(default=None, description="Content ratings to include (omit for all ratings)", alias="contentRating")
    status: Optional[List[StrictStr]] = Field(default=None, description="Segment status filter")
    segment_length_chars: Optional[SearchFiltersSegmentLengthChars] = Field(default=None, alias="segmentLengthChars")
    segment_duration_ms: Optional[SearchFiltersSegmentDurationMs] = Field(default=None, alias="segmentDurationMs")
    languages: Optional[SearchFiltersLanguages] = None
    __properties: ClassVar[List[str]] = ["media", "category", "contentRating", "status", "segmentLengthChars", "segmentDurationMs", "languages"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['DELETED', 'ACTIVE', 'SUSPENDED', 'VERIFIED', 'INVALID', 'TOO_LONG']):
                raise ValueError("each list item must be one of ('DELETED', 'ACTIVE', 'SUSPENDED', 'VERIFIED', 'INVALID', 'TOO_LONG')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchFilters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of media
        if self.media:
            _dict['media'] = self.media.to_dict()
        # override the default output from pydantic by calling `to_dict()` of segment_length_chars
        if self.segment_length_chars:
            _dict['segmentLengthChars'] = self.segment_length_chars.to_dict()
        # override the default output from pydantic by calling `to_dict()` of segment_duration_ms
        if self.segment_duration_ms:
            _dict['segmentDurationMs'] = self.segment_duration_ms.to_dict()
        # override the default output from pydantic by calling `to_dict()` of languages
        if self.languages:
            _dict['languages'] = self.languages.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchFilters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "media": SearchFiltersMedia.from_dict(obj["media"]) if obj.get("media") is not None else None,
            "category": obj.get("category"),
            "contentRating": obj.get("contentRating"),
            "status": obj.get("status"),
            "segmentLengthChars": SearchFiltersSegmentLengthChars.from_dict(obj["segmentLengthChars"]) if obj.get("segmentLengthChars") is not None else None,
            "segmentDurationMs": SearchFiltersSegmentDurationMs.from_dict(obj["segmentDurationMs"]) if obj.get("segmentDurationMs") is not None else None,
            "languages": SearchFiltersLanguages.from_dict(obj["languages"]) if obj.get("languages") is not None else None
        })
        return _obj


