# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from nadeshiko_api_client.models.content_rating import ContentRating
from nadeshiko_api_client.models.segment_text_en import SegmentTextEn
from nadeshiko_api_client.models.segment_text_es import SegmentTextEs
from nadeshiko_api_client.models.segment_text_ja import SegmentTextJa
from nadeshiko_api_client.models.segment_urls import SegmentUrls
from typing import Optional, Set
from typing_extensions import Self

class Segment(BaseModel):
    """
    Segment with content, optional highlights, and media URLs
    """ # noqa: E501
    id: StrictInt = Field(description="Numeric identifier for the segment")
    uuid: StrictStr = Field(description="Unique identifier for the segment")
    public_id: StrictStr = Field(description="Public identifier for the segment (use this instead of uuid in public URLs)", alias="publicId")
    position: StrictInt = Field(description="Position of the segment within the episode")
    status: StrictStr = Field(description="Segment status")
    start_time_ms: StrictInt = Field(description="Start time of the segment in milliseconds from the beginning of the episode", alias="startTimeMs")
    end_time_ms: StrictInt = Field(description="End time of the segment in milliseconds from the beginning of the episode", alias="endTimeMs")
    content_rating: ContentRating = Field(alias="contentRating")
    episode: StrictInt = Field(description="Episode number this segment belongs to")
    media_id: StrictInt = Field(description="Media ID this segment belongs to", alias="mediaId")
    media_public_id: StrictStr = Field(description="Public ID of the media this segment belongs to", alias="mediaPublicId")
    text_ja: SegmentTextJa = Field(alias="textJa")
    text_en: SegmentTextEn = Field(alias="textEn")
    text_es: SegmentTextEs = Field(alias="textEs")
    urls: SegmentUrls
    __properties: ClassVar[List[str]] = ["id", "uuid", "publicId", "position", "status", "startTimeMs", "endTimeMs", "contentRating", "episode", "mediaId", "mediaPublicId", "textJa", "textEn", "textEs", "urls"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['DELETED', 'ACTIVE', 'SUSPENDED', 'VERIFIED', 'INVALID', 'TOO_LONG']):
            raise ValueError("must be one of enum values ('DELETED', 'ACTIVE', 'SUSPENDED', 'VERIFIED', 'INVALID', 'TOO_LONG')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Segment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of text_ja
        if self.text_ja:
            _dict['textJa'] = self.text_ja.to_dict()
        # override the default output from pydantic by calling `to_dict()` of text_en
        if self.text_en:
            _dict['textEn'] = self.text_en.to_dict()
        # override the default output from pydantic by calling `to_dict()` of text_es
        if self.text_es:
            _dict['textEs'] = self.text_es.to_dict()
        # override the default output from pydantic by calling `to_dict()` of urls
        if self.urls:
            _dict['urls'] = self.urls.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Segment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "uuid": obj.get("uuid"),
            "publicId": obj.get("publicId"),
            "position": obj.get("position"),
            "status": obj.get("status"),
            "startTimeMs": obj.get("startTimeMs"),
            "endTimeMs": obj.get("endTimeMs"),
            "contentRating": obj.get("contentRating"),
            "episode": obj.get("episode"),
            "mediaId": obj.get("mediaId"),
            "mediaPublicId": obj.get("mediaPublicId"),
            "textJa": SegmentTextJa.from_dict(obj["textJa"]) if obj.get("textJa") is not None else None,
            "textEn": SegmentTextEn.from_dict(obj["textEn"]) if obj.get("textEn") is not None else None,
            "textEs": SegmentTextEs.from_dict(obj["textEs"]) if obj.get("textEs") is not None else None,
            "urls": SegmentUrls.from_dict(obj["urls"]) if obj.get("urls") is not None else None
        })
        return _obj


