# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from nadeshiko_api_client.models.external_id import ExternalId
from typing import Optional, Set
from typing_extensions import Self

class Seiyuu(BaseModel):
    """
    Japanese voice actor (seiyuu)
    """ # noqa: E501
    id: StrictInt = Field(description="Internal seiyuu ID")
    public_id: StrictStr = Field(description="Public identifier for the seiyuu (use this in public URLs)", alias="publicId")
    external_ids: ExternalId = Field(alias="externalIds")
    name_ja: StrictStr = Field(description="Japanese name of the voice actor", alias="nameJa")
    name_en: StrictStr = Field(description="English name of the voice actor", alias="nameEn")
    image_url: StrictStr = Field(description="Profile image URL", alias="imageUrl")
    __properties: ClassVar[List[str]] = ["id", "publicId", "externalIds", "nameJa", "nameEn", "imageUrl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Seiyuu from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of external_ids
        if self.external_ids:
            _dict['externalIds'] = self.external_ids.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Seiyuu from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "publicId": obj.get("publicId"),
            "externalIds": ExternalId.from_dict(obj["externalIds"]) if obj.get("externalIds") is not None else None,
            "nameJa": obj.get("nameJa"),
            "nameEn": obj.get("nameEn"),
            "imageUrl": obj.get("imageUrl")
        })
        return _obj


