# coding: utf-8

"""
    Nadeshiko API

    Welcome to the Nadeshiko API.   ## Getting Started  Nadeshiko uses API keys to grant access to the API. Authentication is performed using the Authorization header. Please note that you must be registered on Nadeshiko to generate an API key. If you haven't registered yet, please do so.  If you haven't generated an API key yet, you can do so on your [account page](https://nadeshiko.co/settings/api), API section.  ### Quotas and Limits The API has a rate limit to ensure fair usage. Each API key is subject to a rate limit of 2000 requests per 5 minutes. Exceeding this limit will result in a temporary block with the following message:  > \"Too many requests. Please try again later.\"  Additionally, each account has a monthly quota limit based on the user's roles. Once the monthly quota is exceeded, the API key will be temporarily disabled for the rest of the month, and any further requests will receive the message:  > \"API Key quota exceeded for this month.\"  | Role         | Quota (Monthly) | |--------------|-----------------| | Normal User  | 5000 requests   |  To increase your quota, please contact the Nadeshiko team. For more information, refer to the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 1.0.0
    Contact: marc@scalar.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from nadeshiko_api_client.models.basic_info import BasicInfo
from nadeshiko_api_client.models.media_info import MediaInfo
from nadeshiko_api_client.models.segment_info import SegmentInfo
from typing import Optional, Set
from typing_extensions import Self

class Sentence(BaseModel):
    """
    Sentence
    """ # noqa: E501
    basic_info: Optional[BasicInfo] = None
    segment_info: Optional[SegmentInfo] = None
    media_info: Optional[MediaInfo] = None
    __properties: ClassVar[List[str]] = ["basic_info", "segment_info", "media_info"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Sentence from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of basic_info
        if self.basic_info:
            _dict['basic_info'] = self.basic_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of segment_info
        if self.segment_info:
            _dict['segment_info'] = self.segment_info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of media_info
        if self.media_info:
            _dict['media_info'] = self.media_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Sentence from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "basic_info": BasicInfo.from_dict(obj["basic_info"]) if obj.get("basic_info") is not None else None,
            "segment_info": SegmentInfo.from_dict(obj["segment_info"]) if obj.get("segment_info") is not None else None,
            "media_info": MediaInfo.from_dict(obj["media_info"]) if obj.get("media_info") is not None else None
        })
        return _obj


