# coding: utf-8

"""
    Nadeshiko API

    Welcome to the Nadeshiko API.   ## Getting Started  Nadeshiko uses API keys to grant access to the API. Authentication is performed using the Authorization header. Please note that you must be registered on Nadeshiko to generate an API key. If you haven't registered yet, please do so.  If you haven't generated an API key yet, you can do so on your [account page](https://nadeshiko.co/settings/api), API section.  ### Quotas and Limits The API has a rate limit to ensure fair usage. Each API key is subject to a rate limit of 2000 requests per 5 minutes. Exceeding this limit will result in a temporary block with the following message:  > \"Too many requests. Please try again later.\"  Additionally, each account has a monthly quota limit based on the user's roles. Once the monthly quota is exceeded, the API key will be temporarily disabled for the rest of the month, and any further requests will receive the message:  > \"API Key quota exceeded for this month.\"  | Role         | Quota (Monthly) | |--------------|-----------------| | Normal User  | 5000 requests   |  To increase your quota, please contact the Nadeshiko team. For more information, refer to the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 1.0.0
    Contact: marc@scalar.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class SentenceSearchRequest(BaseModel):
    """
    SentenceSearchRequest
    """ # noqa: E501
    query: Optional[StrictStr] = Field(default=None, description="Text or sentence to search")
    limit: Optional[StrictInt] = Field(default=None, description="Max amount of entries by response")
    uuid: Optional[StrictStr] = Field(default=None, description="Unique ID from sentence (Useful to get a specific sentence)")
    category: Optional[StrictInt] = Field(default=None, description="Anime, Liveaction")
    anime_id: Optional[StrictInt] = Field(default=None, description="Unique ID from media")
    season: Optional[List[StrictInt]] = Field(default=None, description="Array of seasons to get")
    episode: Optional[List[StrictInt]] = Field(default=None, description="Array of episodes to get")
    random_seed: Optional[Union[Annotated[float, Field(le=1, strict=True, ge=0)], Annotated[int, Field(le=1, strict=True, ge=0)]]] = Field(default=None, description="A value from 0 to 1")
    content_sort: Optional[StrictStr] = Field(default=None, description="Order by amount of characters")
    cursor: Optional[List[StrictInt]] = Field(default=None, description="Current page of search")
    __properties: ClassVar[List[str]] = ["query", "limit", "uuid", "category", "anime_id", "season", "episode", "random_seed", "content_sort", "cursor"]

    @field_validator('content_sort')
    def content_sort_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ASC', 'DESC']):
            raise ValueError("must be one of enum values ('ASC', 'DESC')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SentenceSearchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SentenceSearchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "limit": obj.get("limit"),
            "uuid": obj.get("uuid"),
            "category": obj.get("category"),
            "anime_id": obj.get("anime_id"),
            "season": obj.get("season"),
            "episode": obj.get("episode"),
            "random_seed": obj.get("random_seed"),
            "content_sort": obj.get("content_sort"),
            "cursor": obj.get("cursor")
        })
        return _obj


