# coding: utf-8

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class Token(BaseModel):
    """
    Morphological token from Japanese text analysis
    """ # noqa: E501
    s: StrictStr = Field(description="Surface form (the text as it appears in the sentence)")
    d: StrictStr = Field(description="Dictionary form (base/lemma form for search)")
    r: StrictStr = Field(description="Reading in katakana")
    b: StrictInt = Field(description="Begin character offset in textJa.content")
    e: StrictInt = Field(description="End character offset in textJa.content")
    p: StrictStr = Field(description="Primary part-of-speech tag")
    p1: Optional[StrictStr] = Field(default=None, description="POS subtype 1 (UniDic pos[1])")
    p2: Optional[StrictStr] = Field(default=None, description="POS subtype 2 (UniDic pos[2])")
    p4: Optional[StrictStr] = Field(default=None, description="Conjugation type (UniDic pos[4])")
    cf: Optional[StrictStr] = Field(default=None, description="Conjugation form (UniDic pos[5])")
    __properties: ClassVar[List[str]] = ["s", "d", "r", "b", "e", "p", "p1", "p2", "p4", "cf"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Token from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Token from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "s": obj.get("s"),
            "d": obj.get("d"),
            "r": obj.get("r"),
            "b": obj.get("b"),
            "e": obj.get("e"),
            "p": obj.get("p"),
            "p1": obj.get("p1"),
            "p2": obj.get("p2"),
            "p4": obj.get("p4"),
            "cf": obj.get("cf")
        })
        return _obj


