# coding: utf-8

# flake8: noqa

"""
    Nadeshiko API

    Thank you for using the Nadeshiko API! This API lets you search Japanese dialogue segments across anime and J-Drama, with translations and contextual metadata.  ### Authentication All API requests require an API key passed as a Bearer token. You can register and generate your key on the [developer page](https://nadeshiko.co/user/developer), where you can also check your current usage.  ### Rate Limit Each API key is limited to **150 requests per minute**. Exceeding this limit will return a `429 Too Many Requests` response.  ### Quota Each account has a monthly quota of **5,000 requests**. Once exceeded, further requests will be rejected until the next month. To request a quota increase, reach out via the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 2.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "MediaApi",
    "SearchApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Category",
    "CategoryCount",
    "ContentRating",
    "Episode",
    "EpisodeListResponse",
    "Error400",
    "Error401",
    "Error403",
    "Error404",
    "Error429",
    "Error500",
    "ExternalId",
    "IncludeExpansion",
    "Media",
    "MediaCharacter",
    "MediaFilterItem",
    "MediaIncludeExpansion",
    "MediaListResponse",
    "MediaListResponseStats",
    "MediaSearchStats",
    "OpaqueCursorPagination",
    "PaginationInfo",
    "SearchFilters",
    "SearchFiltersLanguages",
    "SearchFiltersMedia",
    "SearchFiltersSegmentDurationMs",
    "SearchFiltersSegmentLengthChars",
    "SearchMultipleRequest",
    "SearchMultipleRequestQuery",
    "SearchMultipleResponse",
    "SearchMultipleResponseIncludes",
    "SearchRequest",
    "SearchRequestQuery",
    "SearchRequestSort",
    "SearchResponse",
    "SearchResponseIncludes",
    "SearchStatsRequest",
    "SearchStatsRequestQuery",
    "SearchStatsResponse",
    "Segment",
    "SegmentContextResponse",
    "SegmentContextResponseIncludes",
    "SegmentInternal",
    "SegmentTextEn",
    "SegmentTextEs",
    "SegmentTextJa",
    "SegmentUrls",
    "Seiyuu",
    "Series",
    "SeriesListResponse",
    "SeriesWithMedia",
    "SeriesWithMediaMediaInner",
    "Token",
    "WordMatch",
    "WordMatchMedia",
]

# import apis into sdk package
from nadeshiko_api_client.api.media_api import MediaApi as MediaApi
from nadeshiko_api_client.api.search_api import SearchApi as SearchApi

# import ApiClient
from nadeshiko_api_client.api_response import ApiResponse as ApiResponse
from nadeshiko_api_client.api_client import ApiClient as ApiClient
from nadeshiko_api_client.configuration import Configuration as Configuration
from nadeshiko_api_client.exceptions import OpenApiException as OpenApiException
from nadeshiko_api_client.exceptions import ApiTypeError as ApiTypeError
from nadeshiko_api_client.exceptions import ApiValueError as ApiValueError
from nadeshiko_api_client.exceptions import ApiKeyError as ApiKeyError
from nadeshiko_api_client.exceptions import ApiAttributeError as ApiAttributeError
from nadeshiko_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from nadeshiko_api_client.models.category import Category as Category
from nadeshiko_api_client.models.category_count import CategoryCount as CategoryCount
from nadeshiko_api_client.models.content_rating import ContentRating as ContentRating
from nadeshiko_api_client.models.episode import Episode as Episode
from nadeshiko_api_client.models.episode_list_response import EpisodeListResponse as EpisodeListResponse
from nadeshiko_api_client.models.error400 import Error400 as Error400
from nadeshiko_api_client.models.error401 import Error401 as Error401
from nadeshiko_api_client.models.error403 import Error403 as Error403
from nadeshiko_api_client.models.error404 import Error404 as Error404
from nadeshiko_api_client.models.error429 import Error429 as Error429
from nadeshiko_api_client.models.error500 import Error500 as Error500
from nadeshiko_api_client.models.external_id import ExternalId as ExternalId
from nadeshiko_api_client.models.include_expansion import IncludeExpansion as IncludeExpansion
from nadeshiko_api_client.models.media import Media as Media
from nadeshiko_api_client.models.media_character import MediaCharacter as MediaCharacter
from nadeshiko_api_client.models.media_filter_item import MediaFilterItem as MediaFilterItem
from nadeshiko_api_client.models.media_include_expansion import MediaIncludeExpansion as MediaIncludeExpansion
from nadeshiko_api_client.models.media_list_response import MediaListResponse as MediaListResponse
from nadeshiko_api_client.models.media_list_response_stats import MediaListResponseStats as MediaListResponseStats
from nadeshiko_api_client.models.media_search_stats import MediaSearchStats as MediaSearchStats
from nadeshiko_api_client.models.opaque_cursor_pagination import OpaqueCursorPagination as OpaqueCursorPagination
from nadeshiko_api_client.models.pagination_info import PaginationInfo as PaginationInfo
from nadeshiko_api_client.models.search_filters import SearchFilters as SearchFilters
from nadeshiko_api_client.models.search_filters_languages import SearchFiltersLanguages as SearchFiltersLanguages
from nadeshiko_api_client.models.search_filters_media import SearchFiltersMedia as SearchFiltersMedia
from nadeshiko_api_client.models.search_filters_segment_duration_ms import SearchFiltersSegmentDurationMs as SearchFiltersSegmentDurationMs
from nadeshiko_api_client.models.search_filters_segment_length_chars import SearchFiltersSegmentLengthChars as SearchFiltersSegmentLengthChars
from nadeshiko_api_client.models.search_multiple_request import SearchMultipleRequest as SearchMultipleRequest
from nadeshiko_api_client.models.search_multiple_request_query import SearchMultipleRequestQuery as SearchMultipleRequestQuery
from nadeshiko_api_client.models.search_multiple_response import SearchMultipleResponse as SearchMultipleResponse
from nadeshiko_api_client.models.search_multiple_response_includes import SearchMultipleResponseIncludes as SearchMultipleResponseIncludes
from nadeshiko_api_client.models.search_request import SearchRequest as SearchRequest
from nadeshiko_api_client.models.search_request_query import SearchRequestQuery as SearchRequestQuery
from nadeshiko_api_client.models.search_request_sort import SearchRequestSort as SearchRequestSort
from nadeshiko_api_client.models.search_response import SearchResponse as SearchResponse
from nadeshiko_api_client.models.search_response_includes import SearchResponseIncludes as SearchResponseIncludes
from nadeshiko_api_client.models.search_stats_request import SearchStatsRequest as SearchStatsRequest
from nadeshiko_api_client.models.search_stats_request_query import SearchStatsRequestQuery as SearchStatsRequestQuery
from nadeshiko_api_client.models.search_stats_response import SearchStatsResponse as SearchStatsResponse
from nadeshiko_api_client.models.segment import Segment as Segment
from nadeshiko_api_client.models.segment_context_response import SegmentContextResponse as SegmentContextResponse
from nadeshiko_api_client.models.segment_context_response_includes import SegmentContextResponseIncludes as SegmentContextResponseIncludes
from nadeshiko_api_client.models.segment_internal import SegmentInternal as SegmentInternal
from nadeshiko_api_client.models.segment_text_en import SegmentTextEn as SegmentTextEn
from nadeshiko_api_client.models.segment_text_es import SegmentTextEs as SegmentTextEs
from nadeshiko_api_client.models.segment_text_ja import SegmentTextJa as SegmentTextJa
from nadeshiko_api_client.models.segment_urls import SegmentUrls as SegmentUrls
from nadeshiko_api_client.models.seiyuu import Seiyuu as Seiyuu
from nadeshiko_api_client.models.series import Series as Series
from nadeshiko_api_client.models.series_list_response import SeriesListResponse as SeriesListResponse
from nadeshiko_api_client.models.series_with_media import SeriesWithMedia as SeriesWithMedia
from nadeshiko_api_client.models.series_with_media_media_inner import SeriesWithMediaMediaInner as SeriesWithMediaMediaInner
from nadeshiko_api_client.models.token import Token as Token
from nadeshiko_api_client.models.word_match import WordMatch as WordMatch
from nadeshiko_api_client.models.word_match_media import WordMatchMedia as WordMatchMedia

