# coding: utf-8

# flake8: noqa

"""
    Nadeshiko API

    Welcome to the Nadeshiko API.   ## Getting Started  Nadeshiko uses API keys to grant access to the API. Authentication is performed using the Authorization header. Please note that you must be registered on Nadeshiko to generate an API key. If you haven't registered yet, please do so.  If you haven't generated an API key yet, you can do so on your [account page](https://nadeshiko.co/settings/api), API section.  ### Quotas and Limits The API has a rate limit to ensure fair usage. Each API key is subject to a rate limit of 2000 requests per 5 minutes. Exceeding this limit will result in a temporary block with the following message:  > \"Too many requests. Please try again later.\"  Additionally, each account has a monthly quota limit based on the user's roles. Once the monthly quota is exceeded, the API key will be temporarily disabled for the rest of the month, and any further requests will receive the message:  > \"API Key quota exceeded for this month.\"  | Role         | Quota (Monthly) | |--------------|-----------------| | Normal User  | 5000 requests   |  To increase your quota, please contact the Nadeshiko team. For more information, refer to the [contact page](https://nadeshiko.co/about). 

    The version of the OpenAPI document: 1.0.0
    Contact: marc@scalar.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "SearchApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "BasicInfo",
    "CategoryStatistic",
    "ContextRequest",
    "MediaInfo",
    "ResponseV1",
    "SearchMultipleWordsRequest",
    "SegmentInfo",
    "Sentence",
    "SentenceSearchRequest",
    "Statistic",
]

# import apis into sdk package
from nadeshiko_api_client.api.search_api import SearchApi as SearchApi

# import ApiClient
from nadeshiko_api_client.api_response import ApiResponse as ApiResponse
from nadeshiko_api_client.api_client import ApiClient as ApiClient
from nadeshiko_api_client.configuration import Configuration as Configuration
from nadeshiko_api_client.exceptions import OpenApiException as OpenApiException
from nadeshiko_api_client.exceptions import ApiTypeError as ApiTypeError
from nadeshiko_api_client.exceptions import ApiValueError as ApiValueError
from nadeshiko_api_client.exceptions import ApiKeyError as ApiKeyError
from nadeshiko_api_client.exceptions import ApiAttributeError as ApiAttributeError
from nadeshiko_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from nadeshiko_api_client.models.basic_info import BasicInfo as BasicInfo
from nadeshiko_api_client.models.category_statistic import CategoryStatistic as CategoryStatistic
from nadeshiko_api_client.models.context_request import ContextRequest as ContextRequest
from nadeshiko_api_client.models.media_info import MediaInfo as MediaInfo
from nadeshiko_api_client.models.response_v1 import ResponseV1 as ResponseV1
from nadeshiko_api_client.models.search_multiple_words_request import SearchMultipleWordsRequest as SearchMultipleWordsRequest
from nadeshiko_api_client.models.segment_info import SegmentInfo as SegmentInfo
from nadeshiko_api_client.models.sentence import Sentence as Sentence
from nadeshiko_api_client.models.sentence_search_request import SentenceSearchRequest as SentenceSearchRequest
from nadeshiko_api_client.models.statistic import Statistic as Statistic

